language: python

matrix:
  include:
    - language: python
      python: "3.7"
      env: TOXENV=py37

      # currently the only way to use Python 3.7 with travis
      # https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
      sudo: required
      dist: xenial

    - language: python
      python: "3.6"
      env: TOXENV=py36

    - language: python
      python: "3.5"
      env: TOXENV=py35

    - language: python
      python: "3.4"
      env: TOXENV=py34

    - language: python
      python: "2.7"
      env: TOXENV=py27

    - language: python
      python: "pypy"
      env: TOXENV=pypy

    - language: python
      python: "3.5"
      env: TOXENV=lint

    - language: python
      python: "3.5"
      env: TOXENV=readme

before_script:
  - pip install tox

script:
  - tox
