language: python

python: 3.5

env:
  - TOXENV=py37
  - TOXENV=py36
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=lint
  - TOXENV=readme

before_script:
  - pip install tox

script:
  - tox
