language: python

matrix:
  include:
    - language: python
      python: "3.8"
      env: TOXENV=py38

    - language: python
      python: "3.9"
      env: TOXENV=py39

    - language: python
      python: "3.7"
      env: TOXENV=py37

    - language: python
      python: "pypy"
      env: TOXENV=pypy

    - language: python
      python: "3.8"
      env: TOXENV=lint

    - language: python
      python: "3.8"
      env: TOXENV=readme

before_script:
  - pip install tox

script:
  - tox
